info:
  name: Update SAML Config
  type: http
  seq: 2

http:
  method: PUT
  url: "{{baseUrl}}/api/admin/sps/{{spId}}/saml"
  body:
    type: json
    data: |-
      {
        "entity_id": "http://localhost:3002",
        "acs_urls": ["http://localhost:3002/api/auth/saml/callback"],
        "slo_url": "http://localhost:3002/api/auth/saml/logout",
        "name_id_format": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
        "want_signed_assertions": true,
        "want_signed_requests": false
      }
  auth:
    type: bearer
    token: "{{accessToken}}"

runtime:
  variables:
    - name: baseUrl
      value: https://min-idp.toquinha.online

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
