info:
  name: Update SAML Config
  type: http
  seq: 2

http:
  method: PUT
  url: "{{baseUrl}}/api/admin/sps/{{?spId}}/saml"
  auth:
    type: bearer
    token: "{{sessionId}}"
  body:
    type: json
    data: |-
      {
        "entity_id": "https://app.example.com",
        "acs_urls": ["https://app.example.com/saml/acs"]
      }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
