info:
  name: Update OIDC Config
  type: http
  seq: 2

http:
  method: PUT
  url: "{{baseUrl}}/api/admin/sps/{{spId}}/oidc"
  body:
    type: json
    data: |-
      {
        "client_id": "{{?clientId}}",
        "client_secret": "{{?clientSecret}}",
        "redirect_uris": [
          "{{?redirectUri}}"
        ],
        "grant_types": [
          "authorization_code"
        ],
        "response_types": [
          "code"
        ],
        "scopes": [
          "openid",
          "email",
          "profile"
        ],
        "token_endpoint_auth": "client_secret_basic",
        "pkce_required": false
      }
  auth:
    type: bearer
    token: "{{accessToken}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
