info:
  name: Update OIDC Config
  type: http
  seq: 2

http:
  method: PUT
  url: "{{baseUrl}}/api/admin/sps/{{?spId}}/oidc"
  auth:
    type: bearer
    token: "{{sessionId}}"
  body:
    type: json
    data: |-
      {
        "redirect_uris": ["https://app.example.com/callback"],
        "scopes": ["openid","email"],
        "pkce_required": true
      }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
