info:
  name: Create Role
  type: http
  seq: 2

http:
  method: POST
  url: "{{baseUrl}}/api/admin/roles"
  body:
    type: json
    data: |-
      {
        "name": "readwrite",
        "description": "MinIO ROLE"
      }
  auth:
    type: bearer
    token: "{{accessToken}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
