info:
  name: Update Role
  type: http
  seq: 4

http:
  method: PATCH
  url: "{{baseUrl}}/api/admin/roles/{{?roleId}}"
  body:
    type: json
    data: |-
      {
        "name": "minio",
        "description": "Updated description"
      }
  auth:
    type: bearer
    token: "{{accessToken}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
